# Generated by Django 3.2.4 on 2021-06-14 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_comment_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='poster',
            options={'ordering': ('-created',)},
        ),
    ]
